In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)
n=500

data = ({
    'CustomerID':range(1, 501),
    'Age': np.random.randint(22, 65, n),
    'Gender':np.random.choice(['Male', 'Female'], n),
    'Tenure':np.random.randint(2, 60, n),
    'Usage Frequency':np.random.randint(3, 30, n),
    'Support Calls':np.random.randint(0, 10, n),
    'Payment Delay':np.random.randint(2, 30, n),
    'Subscription Type':np.random.choice(['Basic', 'Standard', 'Premium'], n),
    'Contract Length':np.random.choice(['Monthly', 'Annual', 'Quarterly'], n),
    'Total Spend':np.random.randint(100, 1000, n),
    'Last Interaction':np.random.randint(1, 30, n),
    'Churn':np.random.choice(['Yes', 'No'], n),
})
df_clean = pd.DataFrame(data)

In [ ]:
df_clean

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,60,Female,40,14,9,14,Premium,Annual,666,20,No
1,2,50,Male,23,5,1,18,Premium,Monthly,126,21,Yes
2,3,36,Male,27,22,1,29,Standard,Annual,729,27,Yes
3,4,64,Female,45,28,3,3,Basic,Quarterly,832,18,No
4,5,29,Female,26,24,0,29,Basic,Quarterly,330,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,30,Female,39,17,0,26,Basic,Quarterly,116,15,Yes
496,497,45,Female,31,21,5,11,Premium,Quarterly,373,20,No
497,498,56,Male,10,13,8,22,Premium,Quarterly,784,15,No
498,499,56,Male,35,28,6,15,Premium,Annual,215,1,Yes
499,500,57,Male,54,25,3,8,Basic,Annual,960,25,No

In [ ]:
import numpy as np
df_dirty = df_clean.copy()

# Missing values (25%)
for col in ["Age", "Usage Frequency", "Support Calls", "Payment Delay", "Last Interaction"]:
    mask = np.random.random(len(df_dirty)) < 0.25
    df_dirty.loc[mask, col] = None

# Total Spend outliers (5%)
mask = np.random.random(len(df_dirty)) < 0.05
df_dirty.loc[mask, "Total Spend"] = \
    np.random.uniform(100, 1000, mask.sum())

/tmp/ipykernel_6083/3119077666.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[793.11816274 227.39689853 850.71288992 107.33162337 291.75161566
 654.48308903 437.72176773 985.77405255 127.30532214 998.73835114
 661.26504958 602.83629514 153.56119831 345.995989   932.19641946
 418.82140287 695.48788042 999.54671538 336.76274245 618.47279111
 726.79401343 248.16452191]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_dirty.loc[mask, "Total Spend"] = \

In [ ]:
df_dirty

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,60.0,Female,40,14.0,9.0,14.0,Premium,Annual,666.0,20.0,No
1,2,50.0,Male,23,5.0,NaN,18.0,Premium,Monthly,126.0,NaN,Yes
2,3,36.0,Male,27,NaN,NaN,29.0,Standard,Annual,729.0,27.0,Yes
3,4,64.0,Female,45,28.0,3.0,NaN,Basic,Quarterly,832.0,18.0,No
4,5,29.0,Female,26,24.0,0.0,29.0,Basic,Quarterly,330.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,NaN,Female,39,17.0,0.0,26.0,Basic,Quarterly,116.0,NaN,Yes
496,497,45.0,Female,31,21.0,5.0,11.0,Premium,Quarterly,373.0,20.0,No
497,498,56.0,Male,10,13.0,8.0,22.0,Premium,Quarterly,784.0,NaN,No
498,499,56.0,Male,35,28.0,6.0,15.0,Premium,Annual,215.0,1.0,Yes
499,500,57.0,Male,54,25.0,3.0,8.0,Basic,Annual,960.0,NaN,No

In [ ]:
import os

In [ ]:
print(os.getcwd())

/content

In [ ]:
directory = "Desktop"
filename = "Exported_file.csv"
file_path = os.path.join(directory, filename)

In [ ]:
if not os.path.exists(directory):
    os.makedirs(directory)

with open(file_path, "w") as file:
    file.write("Hello from os module!")

In [ ]:
df_dirty.to_csv("Desktop/Exported_file.csv")

In [ ]:
pd.read_csv("Desktop/Exported_file.csv")

,Unnamed: 0,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,0,1,60.0,Female,40,14.0,9.0,14.0,Premium,Annual,666.0,20.0,No
1,1,2,50.0,Male,23,5.0,NaN,18.0,Premium,Monthly,126.0,NaN,Yes
2,2,3,36.0,Male,27,NaN,NaN,29.0,Standard,Annual,729.0,27.0,Yes
3,3,4,64.0,Female,45,28.0,3.0,NaN,Basic,Quarterly,832.0,18.0,No
4,4,5,29.0,Female,26,24.0,0.0,29.0,Basic,Quarterly,330.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,496,NaN,Female,39,17.0,0.0,26.0,Basic,Quarterly,116.0,NaN,Yes
496,496,497,45.0,Female,31,21.0,5.0,11.0,Premium,Quarterly,373.0,20.0,No
497,497,498,56.0,Male,10,13.0,8.0,22.0,Premium,Quarterly,784.0,NaN,No
498,498,499,56.0,Male,35,28.0,6.0,15.0,Premium,Annual,215.0,1.0,Yes
499,499,500,57.0,Male,54,25.0,3.0,8.0,Basic,Annual,960.0,NaN,No

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
df = pd.read_csv(r"Desktop/customerchurn_dirty.csv")
df

,Unnamed: 0,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,0,1,60.0,Female,40,NaN,9.0,14.0,Premium,Annual,666.0,NaN,No
1,1,2,50.0,Male,23,5.0,NaN,NaN,Premium,Monthly,126.0,21.0,Y
2,2,3,36.0,M,27,22.0,1.0,29.0,Standard,Annual,729.0,NaN,Yes
3,3,4,NaN,Female,45,NaN,3.0,3.0,BASIC,Quarterly,832.0,NaN,No
4,4,5,29.0,Fem,26,24.0,0.0,29.0,Basic,Quarterly,330.0,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,496,30.0,Female,39,17.0,0.0,NaN,Basic,Quarterly,116.0,NaN,Yes
496,496,497,45.0,Female,31,21.0,5.0,11.0,Premium,Quarterly,373.0,20.0,No
497,497,498,56.0,Male,10,13.0,8.0,NaN,Premium,Quarterly,784.0,15.0,No
498,498,499,56.0,Male,35,NaN,6.0,15.0,Premium,Annual,215.0,1.0,Yes
499,499,500,57.0,Male,54,NaN,3.0,8.0,Basic,Annual,960.0,25.0,N

In [ ]:
df.dtypes

Unnamed: 0             int64
CustomerID             int64
Age                  float64
Gender                object
Tenure                object
Usage Frequency      float64
Support Calls        float64
Payment Delay        float64
Subscription Type     object
Contract Length       object
Total Spend          float64
Last Interaction     float64
Churn                 object
dtype: object

In [ ]:
df = pd.concat([df, df.iloc[0:1]])  # demo duplicate
print("Duplicates before drop:", df.duplicated().sum(), "\n")
df.drop_duplicates(inplace=True)
print("After dropping duplicates:\n", df, "\n")

Duplicates before drop: 1

After dropping duplicates:
      Unnamed: 0  CustomerID   Age  Gender Tenure  Usage Frequency  \
0             0           1  60.0  Female     40              NaN
1             1           2  50.0    Male     23              5.0
2             2           3  36.0       M     27             22.0
3             3           4   NaN  Female     45              NaN
4             4           5  29.0     Fem     26             24.0
..          ...         ...   ...     ...    ...              ...
495         495         496  30.0  Female     39             17.0
496         496         497  45.0  Female     31             21.0
497         497         498  56.0    Male     10             13.0
498         498         499  56.0    Male     35              NaN
499         499         500  57.0    Male     54              NaN

     Support Calls  Payment Delay Subscription Type Contract Length  \
0              9.0           14.0           Premium          Annual
1              NaN            NaN           Premium         Monthly
2              1.0           29.0          Standard          Annual
3              3.0            3.0             BASIC       Quarterly
4              0.0           29.0             Basic       Quarterly
..             ...            ...               ...             ...
495            0.0            NaN             Basic       Quarterly
496            5.0           11.0           Premium       Quarterly
497            8.0            NaN           Premium       Quarterly
498            6.0           15.0           Premium          Annual
499            3.0            8.0             Basic          Annual

     Total Spend  Last Interaction Churn
0          666.0               NaN    No
1          126.0              21.0     Y
2          729.0               NaN   Yes
3          832.0               NaN    No
4          330.0               NaN    No
..           ...               ...   ...
495        116.0               NaN   Yes
496        373.0              20.0    No
497        784.0              15.0    No
498        215.0               1.0   Yes
499        960.0              25.0     N

[500 rows x 13 columns]

In [ ]:
print("Missing Values:\n", df.isnull().sum(), "\n")

Missing Values:
 Unnamed: 0             0
CustomerID             0
Age                  121
Gender                 0
Tenure                 0
Usage Frequency      137
Support Calls        127
Payment Delay        124
Subscription Type      0
Contract Length        0
Total Spend            0
Last Interaction     138
Churn                  0
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Tenure'] = df['Tenure'].replace({'5-':5, '4-':4, '9-':9, '7-':7})
df['Gender'] = df['Gender'].replace({'F': 'Female', 'M': 'Male', 'Fem': 'Female', 'm': 'Male', 'f':'Female'})
df['Usage Frequency'] = df['Usage Frequency'].fillna(df['Usage Frequency'].mean())
df['Support Calls'] = df['Support Calls'].fillna(df['Support Calls'].mean())
df['Payment Delay'] = df['Payment Delay'].fillna(df['Payment Delay'].mean())
df['Subscription Type'] = df['Subscription Type'].replace({'BASIC': 'Basic', 'standard': 'Standard', 'Prem': 'Premium'})
df['Total Spend'] = df['Total Spend'].fillna(df['Total Spend'].median())
df['Last Interaction'] = df['Last Interaction'].fillna(df['Last Interaction'].median())
df['Churn'] = df['Churn'].replace({'Y': 'Yes', 'N': 'No'})
print("After fillna & replace:\n", df, "\n")

After fillna & replace:
      Unnamed: 0  CustomerID        Age  Gender Tenure  Usage Frequency  \
0             0           1  60.000000  Female     40        16.369146
1             1           2  50.000000    Male     23         5.000000
2             2           3  36.000000    Male     27        22.000000
3             3           4  43.424802  Female     45        16.369146
4             4           5  29.000000  Female     26        24.000000
..          ...         ...        ...     ...    ...              ...
495         495         496  30.000000  Female     39        17.000000
496         496         497  45.000000  Female     31        21.000000
497         497         498  56.000000    Male     10        13.000000
498         498         499  56.000000    Male     35        16.369146
499         499         500  57.000000    Male     54        16.369146

     Support Calls  Payment Delay Subscription Type Contract Length  \
0         9.000000       14.00000           Premium          Annual
1         4.563003       15.62234           Premium         Monthly
2         1.000000       29.00000          Standard          Annual
3         3.000000        3.00000             Basic       Quarterly
4         0.000000       29.00000             Basic       Quarterly
..             ...            ...               ...             ...
495       0.000000       15.62234             Basic       Quarterly
496       5.000000       11.00000           Premium       Quarterly
497       8.000000       15.62234           Premium       Quarterly
498       6.000000       15.00000           Premium          Annual
499       3.000000        8.00000             Basic          Annual

     Total Spend  Last Interaction Churn
0          666.0              16.0    No
1          126.0              21.0   Yes
2          729.0              16.0   Yes
3          832.0              16.0    No
4          330.0              16.0    No
..           ...               ...   ...
495        116.0              16.0   Yes
496        373.0              20.0    No
497        784.0              15.0    No
498        215.0               1.0   Yes
499        960.0              25.0    No

[500 rows x 13 columns]

In [ ]:
Q1 = df['Total Spend'].quantile(0.25)
Q3 = df['Total Spend'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['Total Spend'] = np.where(df['Total Spend'] > upper, upper,
                                 np.where(df['Total Spend'] < lower, lower, df['Total Spend']))
print("After IQR Outlier Capping:\n", df[['Total Spend']], "\n")

After IQR Outlier Capping:
      Total Spend
0          666.0
1          126.0
2          729.0
3          832.0
4          330.0
..           ...
495        116.0
496        373.0
497        784.0
498        215.0
499        960.0

[500 rows x 1 columns]

In [ ]:
directory = "Desktop"
filename = "customerchurn_clean.csv"
file_path = os.path.join(directory, filename)

In [ ]:
if not os.path.exists(directory):
    os.makedirs(directory)

with open(file_path, "w") as file:
    file.write("Hello from os module!")

In [ ]:
df.to_csv("Desktop/customerchurn_clean.csv")

In [ ]:
pd.read_csv("Desktop/customerchurn_clean.csv")

,Unnamed: 0.1,Unnamed: 0,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,0,0,1,60.000000,Female,40,16.369146,9.000000,14.00000,Premium,Annual,666.0,16.0,No
1,1,1,2,50.000000,Male,23,5.000000,4.563003,15.62234,Premium,Monthly,126.0,21.0,Yes
2,2,2,3,36.000000,Male,27,22.000000,1.000000,29.00000,Standard,Annual,729.0,16.0,Yes
3,3,3,4,43.424802,Female,45,16.369146,3.000000,3.00000,Basic,Quarterly,832.0,16.0,No
4,4,4,5,29.000000,Female,26,24.000000,0.000000,29.00000,Basic,Quarterly,330.0,16.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,495,496,30.000000,Female,39,17.000000,0.000000,15.62234,Basic,Quarterly,116.0,16.0,Yes
496,496,496,497,45.000000,Female,31,21.000000,5.000000,11.00000,Premium,Quarterly,373.0,20.0,No
497,497,497,498,56.000000,Male,10,13.000000,8.000000,15.62234,Premium,Quarterly,784.0,15.0,No
498,498,498,499,56.000000,Male,35,16.369146,6.000000,15.00000,Premium,Annual,215.0,1.0,Yes
499,499,499,500,57.000000,Male,54,16.369146,3.000000,8.00000,Basic,Annual,960.0,25.0,No